# Generated by Django 3.1.7 on 2023-03-06 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pin',
            name='destination_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='pin',
            name='pin_about',
            field=models.TextField(blank=True),
        ),
    ]
