# Generated by Django 3.1.7 on 2023-03-10 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pin', '0002_auto_20230305_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pin',
            name='destination_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
