# Generated by Django 3.1.7 on 2023-03-11 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pin', '0003_auto_20230309_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='pin',
            name='comment_persmissions',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pin',
            name='recommendations',
            field=models.BooleanField(default=True),
        ),
    ]
