# Generated by Django 3.1.7 on 2023-03-11 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pin', '0004_auto_20230310_2329'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pin',
            old_name='comment_persmissions',
            new_name='comment_permissions',
        ),
    ]
