# Generated by Django 3.1.7 on 2023-03-05 11:36

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('board', '0002_auto_20230304_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='is_personalisation',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='BoardCollaborator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permissions', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('add_pin', 'Add pin'), ('delete_pin', 'Delete pin'), ('move_pin', 'Move pin'), ('add_section', 'Add section'), ('delete_section', 'Delete section'), ('move_section', 'Move section'), ('comment', 'Comment'), ('react', 'React'), ('invite_collaborator', 'Invite collaborator'), ('remove_collaborator', 'Remove collaborator')], max_length=20), size=None)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.board')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Board Collaborators',
                'unique_together': {('board', 'user')},
            },
        ),
        migrations.AddField(
            model_name='board',
            name='collaborators',
            field=models.ManyToManyField(related_name='boards', through='board.BoardCollaborator', to=settings.AUTH_USER_MODEL),
        ),
    ]
