# Generated by Django 3.1.7 on 2023-03-05 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_auto_20230305_0636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boardcollaborator',
            name='permissions',
        ),
        migrations.CreateModel(
            name='BoardCollaboratorPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('add_pin', 'Add pin'), ('delete_pin', 'Delete pin'), ('move_pin', 'Move pin'), ('add_section', 'Add section'), ('delete_section', 'Delete section'), ('move_section', 'Move section'), ('comment', 'Comment'), ('react', 'React'), ('invite_collaborator', 'Invite collaborator'), ('remove_collaborator', 'Remove collaborator')], max_length=20)),
                ('collaborator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='board.boardcollaborator')),
            ],
        ),
    ]
