# Generated by Django 3.1.7 on 2023-02-26 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20230226_1437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='country_region',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='gener',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='info',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='languages',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='location',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='pronouns',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='website',
        ),
    ]
