# Generated by Django 3.1.7 on 2023-02-27 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_useraccount_nickname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='nickname',
        ),
    ]
