# Generated by Django 3.1.7 on 2023-03-05 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_remove_useraccount_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='is_registered_with_google',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
