# Generated by Django 3.1.7 on 2023-03-11 20:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20230311_1522'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentEspecificWords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_name', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserPermissionSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_mentions', models.CharField(blank=True, choices=[('anyone_on_pinterest', 'Anyone on Pinterest'), ('only_people_you_follow', 'Only people you follow'), ('turn_off_mentions', 'Turn off mentions for you')], max_length=50)),
                ('messages_friends', models.CharField(blank=True, choices=[('direct_messages', 'Direct messages'), ('message_requests', 'Message requests'), ('ignore', 'Ignore')], max_length=50)),
                ('messages_followers', models.CharField(blank=True, choices=[('direct_messages', 'Direct messages'), ('message_requests', 'Message requests'), ('ignore', 'Ignore')], max_length=50)),
                ('messages_following', models.CharField(blank=True, choices=[('direct_messages', 'Direct messages'), ('message_requests', 'Message requests'), ('ignore', 'Ignore')], max_length=50)),
                ('messages_contact', models.CharField(blank=True, choices=[('direct_messages', 'Direct messages'), ('message_requests', 'Message requests'), ('ignore', 'Ignore')], max_length=50)),
                ('messages_others', models.CharField(blank=True, choices=[('direct_messages', 'Direct messages'), ('message_requests', 'Message requests'), ('ignore', 'Ignore')], max_length=50)),
                ('show_on_standard_pins', models.BooleanField(default=True)),
                ('show_on_idea_pins', models.BooleanField(default=True)),
                ('auto_play_videos', models.BooleanField(default=True)),
                ('hidden_me_comments_especific_words', models.ManyToManyField(blank=True, related_name='comment_especific_words', to='user.CommentEspecificWords')),
                ('hidden_others_comments_especific_words', models.ManyToManyField(blank=True, related_name='comment_especific_words_others', to='user.CommentEspecificWords')),
                ('user_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
