# Generated by Django 3.1.7 on 2023-03-11 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='pronouns',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='following', to='user_profile.UserProfile'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gener',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
