# Generated by Django 3.1.7 on 2023-03-11 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_auto_20230311_1145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='info',
            new_name='about_me',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='location',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='photo/avatars/%Y/%m'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='cover_image',
            field=models.ImageField(blank=True, upload_to='photo/covers/%Y/%m'),
        ),
    ]
