# Generated by Django 3.1.7 on 2023-03-08 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_comment_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentlike',
            name='like_type',
        ),
    ]
