# Generated by Django 3.1.7 on 2023-03-10 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pin', '0002_auto_20230305_2243'),
        ('comments', '0004_remove_commentlike_like_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='pin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='pin.pin'),
        ),
    ]
