# Generated by Django 3.1.7 on 2023-03-10 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pin', '0003_auto_20230309_2107'),
        ('comments', '0005_auto_20230309_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='pin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='pin.pin'),
        ),
    ]
